# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TwitterClient' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for TwitterClient
    pod 'TwitterKit'
    pod 'SVProgressHUD'
    pod 'SwiftyJSON'
    pod 'Alamofire'
    pod 'SDWebImage'
    pod 'AlamofireImage'
    pod 'DZNEmptyDataSet'

    target 'TwitterClientTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
